# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_name', models.CharField(default='', max_length=255, unique=True)),
                ('friendly_name', models.CharField(default='', max_length=255, unique=True)),
                ('pypi_link', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LibSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('lib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Lib')),
                ('uses', models.ManyToManyField(related_name='lib_used_with', to='data.Lib')),
            ],
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(default='', max_length=255, unique=True)),
                ('friendly_name', models.CharField(default='', max_length=255, unique=True)),
                ('repo_addr', models.CharField(default='', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepoSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(unique=True)),
                ('added', models.ManyToManyField(related_name='libs_added', to='data.Lib')),
                ('removed', models.ManyToManyField(related_name='libs_removed', to='data.Lib')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Repo')),
            ],
        ),
    ]
