# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(unique=True)),
                ('deleted', models.DateTimeField(null=True, unique=True)),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_library', to='data.Lib')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Repo')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_library', to='data.Lib')),
            ],
        ),
        migrations.RemoveField(
            model_name='libsnapshot',
            name='lib',
        ),
        migrations.RemoveField(
            model_name='libsnapshot',
            name='uses',
        ),
        migrations.RemoveField(
            model_name='reposnapshot',
            name='added',
        ),
        migrations.RemoveField(
            model_name='reposnapshot',
            name='removed',
        ),
        migrations.RemoveField(
            model_name='reposnapshot',
            name='repo',
        ),
        migrations.DeleteModel(
            name='LibSnapshot',
        ),
        migrations.DeleteModel(
            name='RepoSnapshot',
        ),
        migrations.AlterUniqueTogether(
            name='edge',
            unique_together=set([('source', 'dest', 'repo')]),
        ),
    ]
